### ISSUE TITLE
Project is not building. Lot's of errors :-(

### ISSUE THREAD

**Issue by NathalieSpierings** [hpcsc/OnionArchitecture#1]

**Comment by hpcsc** [comment]
Hi,

Sorry about that. I was in the middle of separating domain model and persistence model, but due to my tight schedule, I was never be able to resume on that. I'll try to take some time in the future to complete it

In the mean time, if you want some working code, just check out earlier commit  that the build is still passing (064dba1339257099f7f1141e3f2cea8975397ecb)

**Comment by hpcsc** [comment]
reverted broken commit, made some upgrade to dependencies, still have a lot of things to clean up though
